export const TransFormString = {
  appName: "NotifyMe",
  newNotification: "New Notifications",
  apply: "Apply",
  copyRight: "CopyRight",
  webSiteURL: "NotifyMe.com",
  followUsOn: "Follow us on",
  supportAndSuggestions: "Support & Suggestions",
  termsAndCondition: "Terms & Conditions",
  privacyAndPolicy: "Privacy and Policy",
  cookies: "cookies",
  quickLinksJobs: "Quick Links for Jobs",
  quickLinksAdmission: "Quick Links for Admissions",
  notifications: "Notifications",
  allNotifications: "All Notifications",
  jobs: "Jobs",
  subTitleJobs: "Notifications related to Jobs",
  admissions: "Admissions",
  subTitleAdmissions: "Notifications related to Admissions",
  others: "Others",
  subTitleOthers: "Other notifications",
  homeCardText:
    "Click on the below links to see a list of all the notifications.",
  lastUpdated: "Last updated",
  allOverIndia: "All over India",
  notificationDetailsHeading: "Complete details about Notification.",
  required: " This field is required.",
  termsNcondition: "Please accept the terms and conditions.",
  passwordMissMatch: "Password do not match.",
  invalidPhoneNumber: "Invalid! should be 10 digit.",
  nameOfNotification: "Notification Name",
  conductAuthority: "Conduct Authority",
  nameOfPost: "Posts",
  labelClass: "Class",
  numberOfVacancy: "Vacancy",
  modeOfApplication: "Apply Type",
  modeOfExam: "Exam Type",
  examStartDate: "Exam Start Date",
  examEndDate: "Exam End Date",
  certificateRequired: "Required",
  applicationFee: "Application Fee",
  examLevel: "Exam Level",
  qualification: "Qualification",
  ageLimit: "Age Limit",
  OfficialWebSite: "Official WebSite",
  notificationDetails: "Notification Details",
  applyLink: "Apply Link",
  hallTicketLink: "Hall Ticket Link",
  resultLink: "Result Link",
  otherLinks: "Other Links",
  notificationDate: "Notification Date",
  applyStartDate: "Apply Start Date",
  applyEndDate: "Apply End Date",
  hallTicketDate: "Hall Ticket Date",
  resultDate: "Result Date",
  isActive: "Active",
  showBadge: "Show Badge",
  state: "State",
  remarks: "Remarks",
  nameOfBoard: "Name Of Board",
  formHeading: "Please fill all the (*) mandatory fields...",
  submit: "Submit",
  addNewJobNotification: "Add New Job Notification",
  addNewAdmNotification: "Add New Admission Notification",
  updateNewAdmNotification: "Update Admission Notification",
  updateJobNotification: "Update Job notification",
  edit: "Edit",
  delete: "Delete",
  allJobs: "All Jobs",
  allAdmissions: "All Admissions",
  whatsAppSupportLink: "https://wa.me/919441317903?text= Hi, I have a query",
  whatsAppApplyLink:
    "https://wa.me/919441317903?text= wanna apply for this post.",
  notificationAddMsg: "Notification added successfully.",
  notificationUpdateMsg: "Notification updated successfully.",
};
